# Generated by Django 2.1.1 on 2018-12-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='image',
        ),
    ]
